"""add nomination order to auction

Revision ID: 09e0b0da55c5
Revises: 4bb2cf72e467
Create Date: 2026-08-09 08:47:42.456636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09e0b0da55c5'
down_revision: Union[str, None] = '4bb2cf72e467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'auctions',
        sa.Column('nomination_order', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'nomination_order')
    # ### end Alembic commands ###
