"""add avatar to user

Revision ID: d7485a6e8ff0
Revises: 09e0b0da55c5
Create Date: 2026-08-09 09:22:19.456987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7485a6e8ff0'
down_revision: Union[str, None] = '09e0b0da55c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_data_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_data_url')
    # ### end Alembic commands ###
