"""One-off migration: rename NCAAF/NCAAMB/NCAAWB Team.name rows in place to
append each school's athletics nickname (e.g. "Alabama" -> "Alabama Crimson
Tide"), matching the new names in seed.py / seed_historical_results.py.

Renames existing rows via UPDATE rather than delete+recreate, so it's safe
to run against a database with already-drafted college teams (rosters,
auction items, and historical results all reference team_id, not name, so
they're untouched). Safe to re-run — rows already renamed just won't match
any old name.
"""

from app.database import SessionLocal
from app.models import Team
from app.seed import NCAAF_TEAMS, NCAAMB_TEAMS, NCAAWB_TEAMS

NICKNAMES = {
    "Abilene Christian": "Abilene Christian Wildcats",
    "Air Force": "Air Force Falcons",
    "Akron": "Akron Zips",
    "Alabama": "Alabama Crimson Tide",
    "Alabama A&M": "Alabama A&M Bulldogs",
    "Alabama State": "Alabama State Hornets",
    "Albany": "Albany Great Danes",
    "Alcorn State": "Alcorn State Braves",
    "American": "American Eagles",
    "Appalachian State": "Appalachian State Mountaineers",
    "Arizona": "Arizona Wildcats",
    "Arizona State": "Arizona State Sun Devils",
    "Arkansas": "Arkansas Razorbacks",
    "Arkansas State": "Arkansas State Red Wolves",
    "Arkansas-Pine Bluff": "Arkansas-Pine Bluff Golden Lions",
    "Army": "Army Black Knights",
    "Auburn": "Auburn Tigers",
    "Austin Peay": "Austin Peay Governors",
    "BYU": "BYU Cougars",
    "Ball State": "Ball State Cardinals",
    "Baylor": "Baylor Bears",
    "Bellarmine": "Bellarmine Knights",
    "Belmont": "Belmont Bruins",
    "Bethune-Cookman": "Bethune-Cookman Wildcats",
    "Binghamton": "Binghamton Bearcats",
    "Boise State": "Boise State Broncos",
    "Boston College": "Boston College Eagles",
    "Boston University": "Boston University Terriers",
    "Bowling Green": "Bowling Green Falcons",
    "Bradley": "Bradley Braves",
    "Brown": "Brown Bears",
    "Bryant": "Bryant Bulldogs",
    "Bucknell": "Bucknell Bison",
    "Buffalo": "Buffalo Bulls",
    "Butler": "Butler Bulldogs",
    "Cal Poly": "Cal Poly Mustangs",
    "Cal State Bakersfield": "Cal State Bakersfield Roadrunners",
    "Cal State Fullerton": "Cal State Fullerton Titans",
    "Cal State Northridge": "Cal State Northridge Matadors",
    "California": "California Golden Bears",
    "California Baptist": "California Baptist Lancers",
    "Campbell": "Campbell Fighting Camels",
    "Canisius": "Canisius Golden Griffins",
    "Central Arkansas": "Central Arkansas Bears",
    "Central Connecticut": "Central Connecticut Blue Devils",
    "Central Michigan": "Central Michigan Chippewas",
    "Charleston": "Charleston Cougars",
    "Charleston Southern": "Charleston Southern Buccaneers",
    "Charlotte": "Charlotte 49ers",
    "Chattanooga": "Chattanooga Mocs",
    "Chicago State": "Chicago State Cougars",
    "Cincinnati": "Cincinnati Bearcats",
    "Clemson": "Clemson Tigers",
    "Cleveland State": "Cleveland State Vikings",
    "Coastal Carolina": "Coastal Carolina Chanticleers",
    "Colgate": "Colgate Raiders",
    "Colorado": "Colorado Buffaloes",
    "Colorado State": "Colorado State Rams",
    "Columbia": "Columbia Lions",
    "Coppin State": "Coppin State Eagles",
    "Cornell": "Cornell Big Red",
    "Creighton": "Creighton Bluejays",
    "Dartmouth": "Dartmouth Big Green",
    "Davidson": "Davidson Wildcats",
    "Dayton": "Dayton Flyers",
    "DePaul": "DePaul Blue Demons",
    "Delaware": "Delaware Blue Hens",
    "Delaware State": "Delaware State Hornets",
    "Denver": "Denver Pioneers",
    "Detroit Mercy": "Detroit Mercy Titans",
    "Drake": "Drake Bulldogs",
    "Drexel": "Drexel Dragons",
    "Duke": "Duke Blue Devils",
    "Duquesne": "Duquesne Dukes",
    "East Carolina": "East Carolina Pirates",
    "East Tennessee State": "East Tennessee State Buccaneers",
    "East Texas A&M": "East Texas A&M Lions",
    "Eastern Illinois": "Eastern Illinois Panthers",
    "Eastern Kentucky": "Eastern Kentucky Colonels",
    "Eastern Michigan": "Eastern Michigan Eagles",
    "Eastern Washington": "Eastern Washington Eagles",
    "Elon": "Elon Phoenix",
    "Evansville": "Evansville Purple Aces",
    "FIU": "FIU Panthers",
    "Fairfield": "Fairfield Stags",
    "Fairleigh Dickinson": "Fairleigh Dickinson Knights",
    "Florida": "Florida Gators",
    "Florida A&M": "Florida A&M Rattlers",
    "Florida Atlantic": "Florida Atlantic Owls",
    "Florida Gulf Coast": "Florida Gulf Coast Eagles",
    "Florida State": "Florida State Seminoles",
    "Fordham": "Fordham Rams",
    "Fresno State": "Fresno State Bulldogs",
    "Furman": "Furman Paladins",
    "Gardner-Webb": "Gardner-Webb Runnin' Bulldogs",
    "George Mason": "George Mason Patriots",
    "George Washington": "George Washington Revolutionaries",
    "Georgetown": "Georgetown Hoyas",
    "Georgia": "Georgia Bulldogs",
    "Georgia Southern": "Georgia Southern Eagles",
    "Georgia State": "Georgia State Panthers",
    "Georgia Tech": "Georgia Tech Yellow Jackets",
    "Gonzaga": "Gonzaga Bulldogs",
    "Grambling State": "Grambling State Tigers",
    "Grand Canyon": "Grand Canyon Antelopes",
    "Green Bay": "Green Bay Phoenix",
    "Hampton": "Hampton Pirates",
    "Harvard": "Harvard Crimson",
    "Hawaii": "Hawaii Rainbow Warriors",
    "High Point": "High Point Panthers",
    "Hofstra": "Hofstra Pride",
    "Holy Cross": "Holy Cross Crusaders",
    "Houston": "Houston Cougars",
    "Houston Christian": "Houston Christian Huskies",
    "Howard": "Howard Bison",
    "IU Indy": "IU Indy Jaguars",
    "Idaho": "Idaho Vandals",
    "Idaho State": "Idaho State Bengals",
    "Illinois": "Illinois Fighting Illini",
    "Illinois State": "Illinois State Redbirds",
    "Incarnate Word": "Incarnate Word Cardinals",
    "Indiana": "Indiana Hoosiers",
    "Indiana State": "Indiana State Sycamores",
    "Iona": "Iona Gaels",
    "Iowa": "Iowa Hawkeyes",
    "Iowa State": "Iowa State Cyclones",
    "Jackson State": "Jackson State Tigers",
    "Jacksonville": "Jacksonville Dolphins",
    "Jacksonville State": "Jacksonville State Gamecocks",
    "James Madison": "James Madison Dukes",
    "Kansas": "Kansas Jayhawks",
    "Kansas City": "Kansas City Roos",
    "Kansas State": "Kansas State Wildcats",
    "Kennesaw State": "Kennesaw State Owls",
    "Kent State": "Kent State Golden Flashes",
    "Kentucky": "Kentucky Wildcats",
    "LIU": "LIU Sharks",
    "LSU": "LSU Tigers",
    "La Salle": "La Salle Explorers",
    "Lafayette": "Lafayette Leopards",
    "Lamar": "Lamar Cardinals",
    "Le Moyne": "Le Moyne Dolphins",
    "Lehigh": "Lehigh Mountain Hawks",
    "Liberty": "Liberty Flames",
    "Lindenwood": "Lindenwood Lions",
    "Lipscomb": "Lipscomb Bisons",
    "Little Rock": "Little Rock Trojans",
    "Long Beach State": "Long Beach State Beach",
    "Longwood": "Longwood Lancers",
    "Louisiana": "Louisiana Ragin' Cajuns",
    "Louisiana Tech": "Louisiana Tech Bulldogs",
    "Louisiana-Monroe": "Louisiana-Monroe Warhawks",
    "Louisville": "Louisville Cardinals",
    "Loyola Chicago": "Loyola Chicago Ramblers",
    "Loyola Maryland": "Loyola Maryland Greyhounds",
    "Loyola Marymount": "Loyola Marymount Lions",
    "Maine": "Maine Black Bears",
    "Manhattan": "Manhattan Jaspers",
    "Marist": "Marist Red Foxes",
    "Marquette": "Marquette Golden Eagles",
    "Marshall": "Marshall Thundering Herd",
    "Maryland": "Maryland Terrapins",
    "Maryland Eastern Shore": "Maryland Eastern Shore Hawks",
    "McNeese State": "McNeese State Cowboys",
    "Memphis": "Memphis Tigers",
    "Mercer": "Mercer Bears",
    "Mercyhurst": "Mercyhurst Lakers",
    "Merrimack": "Merrimack Warriors",
    "Miami (FL)": "Miami (FL) Hurricanes",
    "Miami (OH)": "Miami (OH) RedHawks",
    "Michigan": "Michigan Wolverines",
    "Michigan State": "Michigan State Spartans",
    "Middle Tennessee": "Middle Tennessee Blue Raiders",
    "Milwaukee": "Milwaukee Panthers",
    "Minnesota": "Minnesota Golden Gophers",
    "Mississippi State": "Mississippi State Bulldogs",
    "Mississippi Valley State": "Mississippi Valley State Delta Devils",
    "Missouri": "Missouri Tigers",
    "Missouri State": "Missouri State Bears",
    "Monmouth": "Monmouth Hawks",
    "Montana": "Montana Grizzlies",
    "Montana State": "Montana State Bobcats",
    "Morehead State": "Morehead State Eagles",
    "Morgan State": "Morgan State Bears",
    "Mount St. Mary's": "Mount St. Mary's Mountaineers",
    "Murray State": "Murray State Racers",
    "NC A&T": "NC A&T Aggies",
    "NC State": "NC State Wolfpack",
    "NJIT": "NJIT Highlanders",
    "Navy": "Navy Midshipmen",
    "Nebraska": "Nebraska Cornhuskers",
    "Nevada": "Nevada Wolf Pack",
    "New Hampshire": "New Hampshire Wildcats",
    "New Haven": "New Haven Chargers",
    "New Mexico": "New Mexico Lobos",
    "New Mexico State": "New Mexico State Aggies",
    "New Orleans": "New Orleans Privateers",
    "Niagara": "Niagara Purple Eagles",
    "Nicholls State": "Nicholls State Colonels",
    "Norfolk State": "Norfolk State Spartans",
    "North Alabama": "North Alabama Lions",
    "North Carolina": "North Carolina Tar Heels",
    "North Carolina Central": "North Carolina Central Eagles",
    "North Dakota": "North Dakota Fighting Hawks",
    "North Dakota State": "North Dakota State Bison",
    "North Florida": "North Florida Ospreys",
    "North Texas": "North Texas Mean Green",
    "Northeastern": "Northeastern Huskies",
    "Northern Arizona": "Northern Arizona Lumberjacks",
    "Northern Colorado": "Northern Colorado Bears",
    "Northern Illinois": "Northern Illinois Huskies",
    "Northern Iowa": "Northern Iowa Panthers",
    "Northern Kentucky": "Northern Kentucky Norse",
    "Northwestern": "Northwestern Wildcats",
    "Northwestern State": "Northwestern State Demons",
    "Notre Dame": "Notre Dame Fighting Irish",
    "Oakland": "Oakland Golden Grizzlies",
    "Ohio": "Ohio Bobcats",
    "Ohio State": "Ohio State Buckeyes",
    "Oklahoma": "Oklahoma Sooners",
    "Oklahoma State": "Oklahoma State Cowboys",
    "Old Dominion": "Old Dominion Monarchs",
    "Ole Miss": "Ole Miss Rebels",
    "Omaha": "Omaha Mavericks",
    "Oral Roberts": "Oral Roberts Golden Eagles",
    "Oregon": "Oregon Ducks",
    "Oregon State": "Oregon State Beavers",
    "Pacific": "Pacific Tigers",
    "Penn": "Penn Quakers",
    "Penn State": "Penn State Nittany Lions",
    "Pepperdine": "Pepperdine Waves",
    "Pittsburgh": "Pittsburgh Panthers",
    "Portland": "Portland Pilots",
    "Portland State": "Portland State Vikings",
    "Prairie View A&M": "Prairie View A&M Panthers",
    "Presbyterian": "Presbyterian Blue Hose",
    "Princeton": "Princeton Tigers",
    "Providence": "Providence Friars",
    "Purdue": "Purdue Boilermakers",
    "Purdue Fort Wayne": "Purdue Fort Wayne Mastodons",
    "Queens": "Queens Royals",
    "Quinnipiac": "Quinnipiac Bobcats",
    "Radford": "Radford Highlanders",
    "Rhode Island": "Rhode Island Rams",
    "Rice": "Rice Owls",
    "Richmond": "Richmond Spiders",
    "Rider": "Rider Broncs",
    "Robert Morris": "Robert Morris Colonials",
    "Rutgers": "Rutgers Scarlet Knights",
    "SIU Edwardsville": "SIU Edwardsville Cougars",
    "SMU": "SMU Mustangs",
    "Sacramento State": "Sacramento State Hornets",
    "Sacred Heart": "Sacred Heart Pioneers",
    "Saint Joseph's": "Saint Joseph's Hawks",
    "Saint Louis": "Saint Louis Billikens",
    "Saint Mary's": "Saint Mary's Gaels",
    "Sam Houston": "Sam Houston Bearkats",
    "Samford": "Samford Bulldogs",
    "San Diego": "San Diego Toreros",
    "San Diego State": "San Diego State Aztecs",
    "San Francisco": "San Francisco Dons",
    "San Jose State": "San Jose State Spartans",
    "Santa Clara": "Santa Clara Broncos",
    "Seattle": "Seattle Redhawks",
    "Seton Hall": "Seton Hall Pirates",
    "Siena": "Siena Saints",
    "South Alabama": "South Alabama Jaguars",
    "South Carolina": "South Carolina Gamecocks",
    "South Carolina State": "South Carolina State Bulldogs",
    "South Dakota": "South Dakota Coyotes",
    "South Dakota State": "South Dakota State Jackrabbits",
    "South Florida": "South Florida Bulls",
    "Southeast Missouri State": "Southeast Missouri State Redhawks",
    "Southeastern Louisiana": "Southeastern Louisiana Lions",
    "Southern": "Southern Jaguars",
    "Southern Illinois": "Southern Illinois Salukis",
    "Southern Indiana": "Southern Indiana Screaming Eagles",
    "Southern Miss": "Southern Miss Golden Eagles",
    "Southern Utah": "Southern Utah Thunderbirds",
    "St. Bonaventure": "St. Bonaventure Bonnies",
    "St. John's": "St. John's Red Storm",
    "St. Thomas": "St. Thomas Tommies",
    "Stanford": "Stanford Cardinal",
    "Stephen F. Austin": "Stephen F. Austin Lumberjacks",
    "Stetson": "Stetson Hatters",
    "Stonehill": "Stonehill Skyhawks",
    "Stony Brook": "Stony Brook Seawolves",
    "Syracuse": "Syracuse Orange",
    "TCU": "TCU Horned Frogs",
    "Tarleton State": "Tarleton State Texans",
    "Temple": "Temple Owls",
    "Tennessee": "Tennessee Volunteers",
    "Tennessee State": "Tennessee State Tigers",
    "Tennessee Tech": "Tennessee Tech Golden Eagles",
    "Texas": "Texas Longhorns",
    "Texas A&M": "Texas A&M Aggies",
    "Texas A&M-Corpus Christi": "Texas A&M-Corpus Christi Islanders",
    "Texas Southern": "Texas Southern Tigers",
    "Texas State": "Texas State Bobcats",
    "Texas Tech": "Texas Tech Red Raiders",
    "The Citadel": "The Citadel Bulldogs",
    "Toledo": "Toledo Rockets",
    "Towson": "Towson Tigers",
    "Troy": "Troy Trojans",
    "Tulane": "Tulane Green Wave",
    "Tulsa": "Tulsa Golden Hurricane",
    "UAB": "UAB Blazers",
    "UC Davis": "UC Davis Aggies",
    "UC Irvine": "UC Irvine Anteaters",
    "UC Riverside": "UC Riverside Highlanders",
    "UC San Diego": "UC San Diego Tritons",
    "UC Santa Barbara": "UC Santa Barbara Gauchos",
    "UCF": "UCF Knights",
    "UCLA": "UCLA Bruins",
    "UConn": "UConn Huskies",
    "UIC": "UIC Flames",
    "UMBC": "UMBC Retrievers",
    "UMass": "UMass Minutemen",
    "UMass Lowell": "UMass Lowell River Hawks",
    "UNC Asheville": "UNC Asheville Bulldogs",
    "UNC Greensboro": "UNC Greensboro Spartans",
    "UNC Wilmington": "UNC Wilmington Seahawks",
    "UNLV": "UNLV Rebels",
    "USC": "USC Trojans",
    "USC Upstate": "USC Upstate Spartans",
    "UT Arlington": "UT Arlington Mavericks",
    "UT Martin": "UT Martin Skyhawks",
    "UT Rio Grande Valley": "UT Rio Grande Valley Vaqueros",
    "UTEP": "UTEP Miners",
    "UTSA": "UTSA Roadrunners",
    "Utah": "Utah Utes",
    "Utah State": "Utah State Aggies",
    "Utah Tech": "Utah Tech Trailblazers",
    "Utah Valley": "Utah Valley Wolverines",
    "VCU": "VCU Rams",
    "VMI": "VMI Keydets",
    "Valparaiso": "Valparaiso Beacons",
    "Vanderbilt": "Vanderbilt Commodores",
    "Vermont": "Vermont Catamounts",
    "Villanova": "Villanova Wildcats",
    "Virginia": "Virginia Cavaliers",
    "Virginia Tech": "Virginia Tech Hokies",
    "Wagner": "Wagner Seahawks",
    "Wake Forest": "Wake Forest Demon Deacons",
    "Washington": "Washington Huskies",
    "Washington State": "Washington State Cougars",
    "Weber State": "Weber State Wildcats",
    "West Florida": "West Florida Argonauts",
    "West Georgia": "West Georgia Wolves",
    "West Virginia": "West Virginia Mountaineers",
    "Western Carolina": "Western Carolina Catamounts",
    "Western Illinois": "Western Illinois Leathernecks",
    "Western Kentucky": "Western Kentucky Hilltoppers",
    "Western Michigan": "Western Michigan Broncos",
    "Wichita State": "Wichita State Shockers",
    "William & Mary": "William & Mary Tribe",
    "Winthrop": "Winthrop Eagles",
    "Wisconsin": "Wisconsin Badgers",
    "Wofford": "Wofford Terriers",
    "Wright State": "Wright State Raiders",
    "Wyoming": "Wyoming Cowboys",
    "Xavier": "Xavier Musketeers",
    "Yale": "Yale Bulldogs",
    "Youngstown State": "Youngstown State Penguins",
}


def run() -> None:
    db = SessionLocal()
    renamed = 0
    already_current = 0
    unmatched = 0
    current_names = set(NCAAF_TEAMS) | set(NCAAMB_TEAMS) | set(NCAAWB_TEAMS)
    for team in db.query(Team).filter(Team.league.in_(["NCAAF", "NCAAMB", "NCAAWB"])).all():
        if team.name in current_names:
            already_current += 1
            continue
        new_name = NICKNAMES.get(team.name)
        if new_name is None:
            print(f"  no mapping for existing row: {team.league} {team.name!r}")
            unmatched += 1
            continue
        team.name = new_name
        renamed += 1
    db.commit()
    print(f"renamed={renamed} already_current={already_current} unmatched={unmatched}")


if __name__ == "__main__":
    run()
