"""Loads the fall-auction expected-value proxy prices as each fall-session
team's Team.default_value -- the crib sheet's starting price until a user
overrides it with their own CribSheetEntry.

Run with: python -m app.set_ev_defaults
(or `railway ssh -- python -m app.set_ev_defaults` in production)

FALL_EV_RAW_SCORES below holds each team's relative-strength score within
its league, derived from real preseason odds/ratings research (Vegas win
totals and championship odds for NFL/NBA/NHL/NCAAF, Opta predicted points
for EPL, full-field FPI/T-Rank ratings for NCAAF/NCAAMB, current ATP/WTA
rankings aggregated by country) run through this app's real scoring formulas
(app/league_rules.py). Those are proportional, not final dollar amounts --
calibrate() below turns them into dollars per league:

  - Rank a league's teams by score, and find the one at position
    ROSTER_LIMITS[league] * (number of users) -- i.e. the worst team that's
    still needed to fill every user's roster in that league. That team is
    priced at exactly $1, and every team ranked above it is scaled by the
    same factor (so relative spacing between teams is preserved) and
    rounded to the nearest whole dollar, floored at $1.
  - Everything ranked below that cutoff isn't needed by anyone at any
    price under the model, so it's priced at $0 rather than some token
    floor amount.

This intentionally replaced an earlier version of this script that instead
calibrated to a $1 floor on the single worst team and a league-wide $10
average -- that put the floor in the wrong place (the actual last-needed
team was still worth well over $1) and never zeroed out teams nobody's
projected to draft. Proxy model, not a forecast.

Spring-session leagues (MLB, PGA, LPGA, F1, WNBA, MLS, NWSL, TDF, IPL) are not
covered yet -- their Team.default_value stays null (crib sheet shows blank,
same as before this script existed) until the same pricing pass is done there.
"""

from app.database import SessionLocal
from app.league_rules import ROSTER_LIMITS
from app.models import Team, User

# (league, team name) -> relative-strength score within that league (higher
# is better; NOT a dollar amount -- see calibrate() below). Team names
# already match seed.py's canonical Team.name spelling (e.g. "Los Angeles
# Lakers", not "LA Lakers").
FALL_EV_RAW_SCORES: dict[tuple[str, str], int] = {
    # --- NFL ---
    ('NFL', 'Los Angeles Rams'): 17,
    ('NFL', 'Baltimore Ravens'): 16,
    ('NFL', 'Buffalo Bills'): 15,
    ('NFL', 'Seattle Seahawks'): 14,
    ('NFL', 'New England Patriots'): 14,
    ('NFL', 'Kansas City Chiefs'): 14,
    ('NFL', 'Philadelphia Eagles'): 14,
    ('NFL', 'Detroit Lions'): 14,
    ('NFL', 'Cincinnati Bengals'): 14,
    ('NFL', 'Los Angeles Chargers'): 12,
    ('NFL', 'Houston Texans'): 12,
    ('NFL', 'Green Bay Packers'): 12,
    ('NFL', 'San Francisco 49ers'): 12,
    ('NFL', 'Denver Broncos'): 12,
    ('NFL', 'Chicago Bears'): 12,
    ('NFL', 'Dallas Cowboys'): 12,
    ('NFL', 'Jacksonville Jaguars'): 10,
    ('NFL', 'Pittsburgh Steelers'): 10,
    ('NFL', 'Minnesota Vikings'): 10,
    ('NFL', 'Tampa Bay Buccaneers'): 10,
    ('NFL', 'Indianapolis Colts'): 8,
    ('NFL', 'Washington Commanders'): 8,
    ('NFL', 'New York Giants'): 8,
    ('NFL', 'New Orleans Saints'): 8,
    ('NFL', 'Carolina Panthers'): 8,
    ('NFL', 'Atlanta Falcons'): 6,
    ('NFL', 'Tennessee Titans'): 6,
    ('NFL', 'Las Vegas Raiders'): 4,
    ('NFL', 'New York Jets'): 4,
    ('NFL', 'Cleveland Browns'): 4,
    ('NFL', 'Miami Dolphins'): 1,
    ('NFL', 'Arizona Cardinals'): 1,
    # --- NBA ---
    ('NBA', 'Oklahoma City Thunder'): 21,
    ('NBA', 'San Antonio Spurs'): 20,
    ('NBA', 'New York Knicks'): 16,
    ('NBA', 'Boston Celtics'): 15,
    ('NBA', 'Philadelphia 76ers'): 15,
    ('NBA', 'Detroit Pistons'): 14,
    ('NBA', 'Denver Nuggets'): 14,
    ('NBA', 'Minnesota Timberwolves'): 14,
    ('NBA', 'Cleveland Cavaliers'): 13,
    ('NBA', 'Houston Rockets'): 13,
    ('NBA', 'Toronto Raptors'): 12,
    ('NBA', 'Miami Heat'): 12,
    ('NBA', 'Los Angeles Lakers'): 12,
    ('NBA', 'Indiana Pacers'): 11,
    ('NBA', 'Atlanta Hawks'): 11,
    ('NBA', 'Orlando Magic'): 11,
    ('NBA', 'Portland Trail Blazers'): 11,
    ('NBA', 'Golden State Warriors'): 9,
    ('NBA', 'Charlotte Hornets'): 8,
    ('NBA', 'Phoenix Suns'): 8,
    ('NBA', 'Washington Wizards'): 7,
    ('NBA', 'Utah Jazz'): 7,
    ('NBA', 'Dallas Mavericks'): 7,
    ('NBA', 'Los Angeles Clippers'): 4,
    ('NBA', 'Memphis Grizzlies'): 4,
    ('NBA', 'New Orleans Pelicans'): 4,
    ('NBA', 'Chicago Bulls'): 3,
    ('NBA', 'Milwaukee Bucks'): 3,
    ('NBA', 'Brooklyn Nets'): 1,
    ('NBA', 'Sacramento Kings'): 1,
    # --- NHL ---
    ('NHL', 'Florida Panthers'): 18,
    ('NHL', 'Carolina Hurricanes'): 18,
    ('NHL', 'Colorado Avalanche'): 18,
    ('NHL', 'Edmonton Oilers'): 16,
    ('NHL', 'Vegas Golden Knights'): 16,
    ('NHL', 'Tampa Bay Lightning'): 15,
    ('NHL', 'Dallas Stars'): 14,
    ('NHL', 'Minnesota Wild'): 14,
    ('NHL', 'Montreal Canadiens'): 13,
    ('NHL', 'Washington Capitals'): 13,
    ('NHL', 'Buffalo Sabres'): 11,
    ('NHL', 'Toronto Maple Leafs'): 11,
    ('NHL', 'New Jersey Devils'): 11,
    ('NHL', 'Utah Mammoth'): 11,
    ('NHL', 'Anaheim Ducks'): 11,
    ('NHL', 'Los Angeles Kings'): 11,
    ('NHL', 'Ottawa Senators'): 10,
    ('NHL', 'San Jose Sharks'): 10,
    ('NHL', 'Philadelphia Flyers'): 9,
    ('NHL', 'Columbus Blue Jackets'): 8,
    ('NHL', 'Pittsburgh Penguins'): 8,
    ('NHL', 'Boston Bruins'): 7,
    ('NHL', 'New York Islanders'): 7,
    ('NHL', 'Winnipeg Jets'): 7,
    ('NHL', 'Detroit Red Wings'): 6,
    ('NHL', 'New York Rangers'): 6,
    ('NHL', 'Nashville Predators'): 6,
    ('NHL', 'St. Louis Blues'): 5,
    ('NHL', 'Seattle Kraken'): 4,
    ('NHL', 'Chicago Blackhawks'): 3,
    ('NHL', 'Calgary Flames'): 2,
    ('NHL', 'Vancouver Canucks'): 1,
    # --- EPL ---
    ('EPL', 'Arsenal'): 27,
    ('EPL', 'Manchester City'): 21,
    ('EPL', 'Liverpool'): 17,
    ('EPL', 'Manchester United'): 16,
    ('EPL', 'Aston Villa'): 13,
    ('EPL', 'Chelsea'): 13,
    ('EPL', 'Newcastle United'): 11,
    ('EPL', 'Brighton & Hove Albion'): 10,
    ('EPL', 'Tottenham Hotspur'): 10,
    ('EPL', 'Bournemouth'): 9,
    ('EPL', 'Everton'): 9,
    ('EPL', 'Brentford'): 7,
    ('EPL', 'Nottingham Forest'): 7,
    ('EPL', 'Crystal Palace'): 6,
    ('EPL', 'Leeds United'): 6,
    ('EPL', 'Fulham'): 5,
    ('EPL', 'Sunderland'): 5,
    ('EPL', 'Coventry City'): 4,
    ('EPL', 'Ipswich Town'): 3,
    ('EPL', 'Hull City'): 1,
    # --- URC ---
    ('URC', 'Glasgow Warriors'): 17,
    ('URC', 'Leinster'): 16,
    ('URC', 'Stormers'): 14,
    ('URC', 'Bulls'): 14,
    ('URC', 'Munster'): 12,
    ('URC', 'Cardiff'): 12,
    ('URC', 'Lions'): 12,
    ('URC', 'Connacht'): 12,
    ('URC', 'Ulster'): 11,
    ('URC', 'Sharks'): 9,
    ('URC', 'Ospreys'): 8,
    ('URC', 'Edinburgh'): 7,
    ('URC', 'Benetton'): 6,
    ('URC', 'Scarlets'): 4,
    ('URC', 'Dragons'): 4,
    ('URC', 'Zebre Parma'): 1,
    # --- NCAAF ---
    ('NCAAF', 'Ohio State Buckeyes'): 23,
    ('NCAAF', 'Georgia Bulldogs'): 22,
    ('NCAAF', 'Texas Longhorns'): 22,
    ('NCAAF', 'Indiana Hoosiers'): 22,
    ('NCAAF', 'Oregon Ducks'): 22,
    ('NCAAF', 'Notre Dame Fighting Irish'): 22,
    ('NCAAF', 'Alabama Crimson Tide'): 21,
    ('NCAAF', 'LSU Tigers'): 21,
    ('NCAAF', 'Texas A&M Aggies'): 21,
    ('NCAAF', 'Miami (FL) Hurricanes'): 21,
    ('NCAAF', 'Texas Tech Red Raiders'): 21,
    ('NCAAF', 'Oklahoma Sooners'): 20,
    ('NCAAF', 'USC Trojans'): 20,
    ('NCAAF', 'Ole Miss Rebels'): 19,
    ('NCAAF', 'Tennessee Volunteers'): 19,
    ('NCAAF', 'Michigan Wolverines'): 19,
    ('NCAAF', 'Auburn Tigers'): 18,
    ('NCAAF', 'Florida Gators'): 18,
    ('NCAAF', 'Missouri Tigers'): 18,
    ('NCAAF', 'Penn State Nittany Lions'): 18,
    ('NCAAF', 'Clemson Tigers'): 18,
    ('NCAAF', 'BYU Cougars'): 18,
    ('NCAAF', 'South Carolina Gamecocks'): 17,
    ('NCAAF', 'Iowa Hawkeyes'): 17,
    ('NCAAF', 'Washington Huskies'): 17,
    ('NCAAF', 'SMU Mustangs'): 17,
    ('NCAAF', 'Vanderbilt Commodores'): 16,
    ('NCAAF', 'Nebraska Cornhuskers'): 16,
    ('NCAAF', 'Florida State Seminoles'): 16,
    ('NCAAF', 'Louisville Cardinals'): 16,
    ('NCAAF', 'Utah Utes'): 16,
    ('NCAAF', 'Pittsburgh Panthers'): 15,
    ('NCAAF', 'Virginia Cavaliers'): 15,
    ('NCAAF', 'Virginia Tech Hokies'): 15,
    ('NCAAF', 'Arizona Wildcats'): 15,
    ('NCAAF', 'Baylor Bears'): 15,
    ('NCAAF', 'Houston Cougars'): 15,
    ('NCAAF', 'Kentucky Wildcats'): 14,
    ('NCAAF', 'Illinois Fighting Illini'): 14,
    ('NCAAF', 'North Carolina Tar Heels'): 14,
    ('NCAAF', 'Kansas State Wildcats'): 14,
    ('NCAAF', 'TCU Horned Frogs'): 14,
    ('NCAAF', 'Arkansas Razorbacks'): 13,
    ('NCAAF', 'Mississippi State Bulldogs'): 13,
    ('NCAAF', 'Wisconsin Badgers'): 13,
    ('NCAAF', 'Duke Blue Devils'): 13,
    ('NCAAF', 'Georgia Tech Yellow Jackets'): 13,
    ('NCAAF', 'NC State Wolfpack'): 13,
    ('NCAAF', 'Arizona State Sun Devils'): 13,
    ('NCAAF', 'Cincinnati Bearcats'): 13,
    ('NCAAF', 'Colorado Buffaloes'): 13,
    ('NCAAF', 'Boise State Broncos'): 13,
    ('NCAAF', 'Wake Forest Demon Deacons'): 12,
    ('NCAAF', 'Kansas Jayhawks'): 12,
    ('NCAAF', 'Oklahoma State Cowboys'): 12,
    ('NCAAF', 'UCF Knights'): 12,
    ('NCAAF', 'Tulane Green Wave'): 12,
    ('NCAAF', 'Maryland Terrapins'): 11,
    ('NCAAF', 'Northwestern Wildcats'): 11,
    ('NCAAF', 'California Golden Bears'): 11,
    ('NCAAF', 'San Diego State Aztecs'): 11,
    ('NCAAF', 'UNLV Rebels'): 11,
    ('NCAAF', 'Michigan State Spartans'): 10,
    ('NCAAF', 'Minnesota Golden Gophers'): 10,
    ('NCAAF', 'Rutgers Scarlet Knights'): 10,
    ('NCAAF', 'UCLA Bruins'): 10,
    ('NCAAF', 'West Virginia Mountaineers'): 10,
    ('NCAAF', 'East Carolina Pirates'): 10,
    ('NCAAF', 'Navy Midshipmen'): 10,
    ('NCAAF', 'Purdue Boilermakers'): 9,
    ('NCAAF', 'Syracuse Orange'): 9,
    ('NCAAF', 'Iowa State Cyclones'): 9,
    ('NCAAF', 'Memphis Tigers'): 9,
    ('NCAAF', 'South Florida Bulls'): 9,
    ('NCAAF', 'James Madison Dukes'): 9,
    ('NCAAF', 'Boston College Eagles'): 8,
    ('NCAAF', 'Stanford Cardinal'): 8,
    ('NCAAF', 'Fresno State Bulldogs'): 8,
    ('NCAAF', 'Hawaii Rainbow Warriors'): 8,
    ('NCAAF', 'New Mexico Lobos'): 8,
    ('NCAAF', 'Toledo Rockets'): 8,
    ('NCAAF', 'Texas State Bobcats'): 7,
    ('NCAAF', 'Washington State Cougars'): 7,
    ('NCAAF', 'Old Dominion Monarchs'): 7,
    ('NCAAF', 'Western Michigan Broncos'): 7,
    ('NCAAF', 'Western Kentucky Hilltoppers'): 7,
    ('NCAAF', 'Army Black Knights'): 6,
    ('NCAAF', 'North Texas Mean Green'): 6,
    ('NCAAF', 'UTSA Roadrunners'): 6,
    ('NCAAF', 'Southern Miss Golden Eagles'): 6,
    ('NCAAF', 'Delaware Blue Hens'): 6,
    ('NCAAF', 'Oregon State Beavers'): 5,
    ('NCAAF', 'Utah State Aggies'): 5,
    ('NCAAF', 'Air Force Falcons'): 5,
    ('NCAAF', 'North Dakota State Bison'): 5,
    ('NCAAF', 'Louisiana Ragin\' Cajuns'): 5,
    ('NCAAF', 'Troy Trojans'): 5,
    ('NCAAF', 'Miami (OH) RedHawks'): 5,
    ('NCAAF', 'Ohio Bobcats'): 5,
    ('NCAAF', 'Liberty Flames'): 5,
    ('NCAAF', 'Temple Owls'): 4,
    ('NCAAF', 'Tulsa Golden Hurricane'): 4,
    ('NCAAF', 'Appalachian State Mountaineers'): 4,
    ('NCAAF', 'Arkansas State Red Wolves'): 4,
    ('NCAAF', 'Georgia Southern Eagles'): 4,
    ('NCAAF', 'Louisiana Tech Bulldogs'): 4,
    ('NCAAF', 'Marshall Thundering Herd'): 4,
    ('NCAAF', 'South Alabama Jaguars'): 4,
    ('NCAAF', 'Sacramento State Hornets'): 4,
    ('NCAAF', 'Jacksonville State Gamecocks'): 4,
    ('NCAAF', 'Kennesaw State Owls'): 4,
    ('NCAAF', 'Missouri State Bears'): 4,
    ('NCAAF', 'Colorado State Rams'): 3,
    ('NCAAF', 'Nevada Wolf Pack'): 3,
    ('NCAAF', 'Wyoming Cowboys'): 3,
    ('NCAAF', 'Florida Atlantic Owls'): 3,
    ('NCAAF', 'Coastal Carolina Chanticleers'): 3,
    ('NCAAF', 'Buffalo Bulls'): 3,
    ('NCAAF', 'Central Michigan Chippewas'): 3,
    ('NCAAF', 'FIU Panthers'): 3,
    ('NCAAF', 'UConn Huskies'): 3,
    ('NCAAF', 'Northern Illinois Huskies'): 2,
    ('NCAAF', 'San Jose State Spartans'): 2,
    ('NCAAF', 'UTEP Miners'): 2,
    ('NCAAF', 'Charlotte 49ers'): 2,
    ('NCAAF', 'Rice Owls'): 2,
    ('NCAAF', 'UAB Blazers'): 2,
    ('NCAAF', 'Georgia State Panthers'): 2,
    ('NCAAF', 'Bowling Green Falcons'): 2,
    ('NCAAF', 'Eastern Michigan Eagles'): 2,
    ('NCAAF', 'Middle Tennessee Blue Raiders'): 2,
    ('NCAAF', 'New Mexico State Aggies'): 2,
    ('NCAAF', 'Louisiana-Monroe Warhawks'): 1,
    ('NCAAF', 'Akron Zips'): 1,
    ('NCAAF', 'Ball State Cardinals'): 1,
    ('NCAAF', 'Kent State Golden Flashes'): 1,
    ('NCAAF', 'UMass Minutemen'): 1,
    ('NCAAF', 'Sam Houston Bearkats'): 1,
    # --- NCAAMB ---
    ('NCAAMB', 'Duke Blue Devils'): 25,
    ('NCAAMB', 'Louisville Cardinals'): 24,
    ('NCAAMB', 'Virginia Cavaliers'): 24,
    ('NCAAMB', 'Illinois Fighting Illini'): 24,
    ('NCAAMB', 'Michigan State Spartans'): 24,
    ('NCAAMB', 'Arizona Wildcats'): 24,
    ('NCAAMB', 'Houston Cougars'): 24,
    ('NCAAMB', 'Gonzaga Bulldogs'): 24,
    ('NCAAMB', 'Florida Gators'): 24,
    ('NCAAMB', 'UConn Huskies'): 23,
    ('NCAAMB', 'Michigan Wolverines'): 23,
    ('NCAAMB', 'Nebraska Cornhuskers'): 23,
    ('NCAAMB', 'Kansas Jayhawks'): 23,
    ('NCAAMB', 'Texas Tech Red Raiders'): 23,
    ('NCAAMB', 'Tennessee Volunteers'): 23,
    ('NCAAMB', 'Texas Longhorns'): 23,
    ('NCAAMB', 'Miami (FL) Hurricanes'): 22,
    ('NCAAMB', 'St. John\'s Red Storm'): 22,
    ('NCAAMB', 'Ohio State Buckeyes'): 22,
    ('NCAAMB', 'UCLA Bruins'): 22,
    ('NCAAMB', 'Iowa State Cyclones'): 22,
    ('NCAAMB', 'Alabama Crimson Tide'): 22,
    ('NCAAMB', 'Arkansas Razorbacks'): 22,
    ('NCAAMB', 'Kentucky Wildcats'): 22,
    ('NCAAMB', 'Vanderbilt Commodores'): 22,
    ('NCAAMB', 'Marquette Golden Eagles'): 21,
    ('NCAAMB', 'Villanova Wildcats'): 21,
    ('NCAAMB', 'Indiana Hoosiers'): 21,
    ('NCAAMB', 'Oregon Ducks'): 21,
    ('NCAAMB', 'Purdue Boilermakers'): 21,
    ('NCAAMB', 'USC Trojans'): 21,
    ('NCAAMB', 'Georgia Bulldogs'): 21,
    ('NCAAMB', 'Clemson Tigers'): 20,
    ('NCAAMB', 'NC State Wolfpack'): 20,
    ('NCAAMB', 'Virginia Tech Hokies'): 20,
    ('NCAAMB', 'Creighton Bluejays'): 20,
    ('NCAAMB', 'Maryland Terrapins'): 20,
    ('NCAAMB', 'BYU Cougars'): 20,
    ('NCAAMB', 'Cincinnati Bearcats'): 20,
    ('NCAAMB', 'Auburn Tigers'): 20,
    ('NCAAMB', 'Missouri Tigers'): 20,
    ('NCAAMB', 'Oklahoma Sooners'): 20,
    ('NCAAMB', 'North Carolina Tar Heels'): 19,
    ('NCAAMB', 'SMU Mustangs'): 19,
    ('NCAAMB', 'Iowa Hawkeyes'): 19,
    ('NCAAMB', 'Wisconsin Badgers'): 19,
    ('NCAAMB', 'Baylor Bears'): 19,
    ('NCAAMB', 'TCU Horned Frogs'): 19,
    ('NCAAMB', 'UCF Knights'): 19,
    ('NCAAMB', 'LSU Tigers'): 19,
    ('NCAAMB', 'Texas A&M Aggies'): 19,
    ('NCAAMB', 'Syracuse Orange'): 18,
    ('NCAAMB', 'VCU Rams'): 18,
    ('NCAAMB', 'Providence Friars'): 18,
    ('NCAAMB', 'Xavier Musketeers'): 18,
    ('NCAAMB', 'Oklahoma State Cowboys'): 18,
    ('NCAAMB', 'West Virginia Mountaineers'): 18,
    ('NCAAMB', 'Grand Canyon Antelopes'): 18,
    ('NCAAMB', 'San Diego State Aztecs'): 18,
    ('NCAAMB', 'Wichita State Shockers'): 17,
    ('NCAAMB', 'Florida State Seminoles'): 17,
    ('NCAAMB', 'Saint Louis Billikens'): 17,
    ('NCAAMB', 'DePaul Blue Demons'): 17,
    ('NCAAMB', 'High Point Panthers'): 17,
    ('NCAAMB', 'Washington Huskies'): 17,
    ('NCAAMB', 'Arizona State Sun Devils'): 17,
    ('NCAAMB', 'New Mexico Lobos'): 17,
    ('NCAAMB', 'Utah State Aggies'): 17,
    ('NCAAMB', 'Saint Mary\'s Gaels'): 17,
    ('NCAAMB', 'Pittsburgh Panthers'): 16,
    ('NCAAMB', 'Dayton Flyers'): 16,
    ('NCAAMB', 'Seton Hall Pirates'): 16,
    ('NCAAMB', 'Northwestern Wildcats'): 16,
    ('NCAAMB', 'Rutgers Scarlet Knights'): 16,
    ('NCAAMB', 'Utah Utes'): 16,
    ('NCAAMB', 'Mississippi State Bulldogs'): 16,
    ('NCAAMB', 'South Carolina Gamecocks'): 16,
    ('NCAAMB', 'Tulsa Golden Hurricane'): 15,
    ('NCAAMB', 'California Golden Bears'): 15,
    ('NCAAMB', 'Notre Dame Fighting Irish'): 15,
    ('NCAAMB', 'George Washington Revolutionaries'): 15,
    ('NCAAMB', 'Georgetown Hoyas'): 15,
    ('NCAAMB', 'Minnesota Golden Gophers'): 15,
    ('NCAAMB', 'Colorado Buffaloes'): 15,
    ('NCAAMB', 'Kansas State Wildcats'): 15,
    ('NCAAMB', 'Nevada Wolf Pack'): 15,
    ('NCAAMB', 'Boise State Broncos'): 15,
    ('NCAAMB', 'Colorado State Rams'): 15,
    ('NCAAMB', 'McNeese State Cowboys'): 15,
    ('NCAAMB', 'Charlotte 49ers'): 14,
    ('NCAAMB', 'South Florida Bulls'): 14,
    ('NCAAMB', 'Wake Forest Demon Deacons'): 14,
    ('NCAAMB', 'George Mason Patriots'): 14,
    ('NCAAMB', 'Butler Bulldogs'): 14,
    ('NCAAMB', 'UNLV Rebels'): 14,
    ('NCAAMB', 'Oregon State Beavers'): 14,
    ('NCAAMB', 'Santa Clara Broncos'): 14,
    ('NCAAMB', 'Memphis Tigers'): 13,
    ('NCAAMB', 'Boston College Eagles'): 13,
    ('NCAAMB', 'Georgia Tech Yellow Jackets'): 13,
    ('NCAAMB', 'Stanford Cardinal'): 13,
    ('NCAAMB', 'Penn State Nittany Lions'): 13,
    ('NCAAMB', 'UC Santa Barbara Gauchos'): 13,
    ('NCAAMB', 'UNC Wilmington Seahawks'): 13,
    ('NCAAMB', 'Western Kentucky Hilltoppers'): 13,
    ('NCAAMB', 'Miami (OH) RedHawks'): 13,
    ('NCAAMB', 'Illinois State Redbirds'): 13,
    ('NCAAMB', 'Murray State Racers'): 13,
    ('NCAAMB', 'UIC Flames'): 13,
    ('NCAAMB', 'North Texas Mean Green'): 12,
    ('NCAAMB', 'UAB Blazers'): 12,
    ('NCAAMB', 'Davidson Wildcats'): 12,
    ('NCAAMB', 'Richmond Spiders'): 12,
    ('NCAAMB', 'St. Bonaventure Bonnies'): 12,
    ('NCAAMB', 'Harvard Crimson'): 12,
    ('NCAAMB', 'Akron Zips'): 12,
    ('NCAAMB', 'Belmont Bruins'): 12,
    ('NCAAMB', 'Northern Iowa Panthers'): 12,
    ('NCAAMB', 'Hawaii Rainbow Warriors'): 12,
    ('NCAAMB', 'Wyoming Cowboys'): 12,
    ('NCAAMB', 'Fresno State Bulldogs'): 12,
    ('NCAAMB', 'Stephen F. Austin Lumberjacks'): 12,
    ('NCAAMB', 'Florida Atlantic Owls'): 11,
    ('NCAAMB', 'Fordham Rams'): 11,
    ('NCAAMB', 'Saint Joseph\'s Hawks'): 11,
    ('NCAAMB', 'UC Irvine Anteaters'): 11,
    ('NCAAMB', 'UC San Diego Tritons'): 11,
    ('NCAAMB', 'Utah Valley Wolverines'): 11,
    ('NCAAMB', 'Kennesaw State Owls'): 11,
    ('NCAAMB', 'Penn Quakers'): 11,
    ('NCAAMB', 'Toledo Rockets'): 11,
    ('NCAAMB', 'Texas State Bobcats'): 11,
    ('NCAAMB', 'Loyola Marymount Lions'): 11,
    ('NCAAMB', 'Pacific Tigers'): 11,
    ('NCAAMB', 'San Diego Toreros'): 11,
    ('NCAAMB', 'Temple Owls'): 10,
    ('NCAAMB', 'Duquesne Dukes'): 10,
    ('NCAAMB', 'La Salle Explorers'): 10,
    ('NCAAMB', 'Loyola Chicago Ramblers'): 10,
    ('NCAAMB', 'Rhode Island Rams'): 10,
    ('NCAAMB', 'Liberty Flames'): 10,
    ('NCAAMB', 'Middle Tennessee Blue Raiders'): 10,
    ('NCAAMB', 'Robert Morris Colonials'): 10,
    ('NCAAMB', 'Wright State Raiders'): 10,
    ('NCAAMB', 'Kent State Golden Flashes'): 10,
    ('NCAAMB', 'Drake Bulldogs'): 10,
    ('NCAAMB', 'Valparaiso Beacons'): 10,
    ('NCAAMB', 'North Dakota State Bison'): 10,
    ('NCAAMB', 'St. Thomas Tommies'): 10,
    ('NCAAMB', 'James Madison Dukes'): 10,
    ('NCAAMB', 'Tarleton State Texans'): 10,
    ('NCAAMB', 'Pepperdine Waves'): 10,
    ('NCAAMB', 'Seattle Redhawks'): 10,
    ('NCAAMB', 'Tulane Green Wave'): 9,
    ('NCAAMB', 'Montana State Bobcats'): 9,
    ('NCAAMB', 'California Baptist Lancers'): 9,
    ('NCAAMB', 'Sacramento State Hornets'): 9,
    ('NCAAMB', 'Campbell Fighting Camels'): 9,
    ('NCAAMB', 'Hofstra Pride'): 9,
    ('NCAAMB', 'Towson Tigers'): 9,
    ('NCAAMB', 'New Mexico State Aggies'): 9,
    ('NCAAMB', 'Sam Houston Bearkats'): 9,
    ('NCAAMB', 'Princeton Tigers'): 9,
    ('NCAAMB', 'Merrimack Warriors'): 9,
    ('NCAAMB', 'Bowling Green Falcons'): 9,
    ('NCAAMB', 'Eastern Michigan Eagles'): 9,
    ('NCAAMB', 'Western Michigan Broncos'): 9,
    ('NCAAMB', 'UC Davis Aggies'): 9,
    ('NCAAMB', 'San Jose State Spartans'): 9,
    ('NCAAMB', 'UTEP Miners'): 9,
    ('NCAAMB', 'Washington State Cougars'): 9,
    ('NCAAMB', 'East Tennessee State Buccaneers'): 9,
    ('NCAAMB', 'Furman Paladins'): 9,
    ('NCAAMB', 'Western Carolina Catamounts'): 9,
    ('NCAAMB', 'Texas A&M-Corpus Christi Islanders'): 9,
    ('NCAAMB', 'Troy Trojans'): 9,
    ('NCAAMB', 'Austin Peay Governors'): 9,
    ('NCAAMB', 'Central Arkansas Bears'): 9,
    ('NCAAMB', 'Portland Pilots'): 9,
    ('NCAAMB', 'San Francisco Dons'): 9,
    ('NCAAMB', 'Vermont Catamounts'): 8,
    ('NCAAMB', 'East Carolina Pirates'): 8,
    ('NCAAMB', 'Eastern Washington Eagles'): 8,
    ('NCAAMB', 'Charleston Cougars'): 8,
    ('NCAAMB', 'Hampton Pirates'): 8,
    ('NCAAMB', 'William & Mary Tribe'): 8,
    ('NCAAMB', 'FIU Panthers'): 8,
    ('NCAAMB', 'Green Bay Phoenix'): 8,
    ('NCAAMB', 'Columbia Lions'): 8,
    ('NCAAMB', 'Yale Bulldogs'): 8,
    ('NCAAMB', 'UMass Minutemen'): 8,
    ('NCAAMB', 'Ohio Bobcats'): 8,
    ('NCAAMB', 'American Eagles'): 8,
    ('NCAAMB', 'Bethune-Cookman Wildcats'): 8,
    ('NCAAMB', 'Arkansas State Red Wolves'): 8,
    ('NCAAMB', 'Southern Miss Golden Eagles'): 8,
    ('NCAAMB', 'UTSA Roadrunners'): 7,
    ('NCAAMB', 'Jacksonville Dolphins'): 7,
    ('NCAAMB', 'Queens Royals'): 7,
    ('NCAAMB', 'Idaho Vandals'): 7,
    ('NCAAMB', 'Montana Grizzlies'): 7,
    ('NCAAMB', 'Northern Colorado Bears'): 7,
    ('NCAAMB', 'Portland State Vikings'): 7,
    ('NCAAMB', 'Longwood Lancers'): 7,
    ('NCAAMB', 'Winthrop Eagles'): 7,
    ('NCAAMB', 'Cal Poly Mustangs'): 7,
    ('NCAAMB', 'Cal State Fullerton Titans'): 7,
    ('NCAAMB', 'Stony Brook Seawolves'): 7,
    ('NCAAMB', 'Jacksonville State Gamecocks'): 7,
    ('NCAAMB', 'Northern Kentucky Norse'): 7,
    ('NCAAMB', 'Oakland Golden Grizzlies'): 7,
    ('NCAAMB', 'Brown Bears'): 7,
    ('NCAAMB', 'Cornell Big Red'): 7,
    ('NCAAMB', 'Fairfield Stags'): 7,
    ('NCAAMB', 'Marist Red Foxes'): 7,
    ('NCAAMB', 'Quinnipiac Bobcats'): 7,
    ('NCAAMB', 'Buffalo Bulls'): 7,
    ('NCAAMB', 'Central Michigan Chippewas'): 7,
    ('NCAAMB', 'Howard Bison'): 7,
    ('NCAAMB', 'Bradley Braves'): 7,
    ('NCAAMB', 'Indiana State Sycamores'): 7,
    ('NCAAMB', 'Southeast Missouri State Redhawks'): 7,
    ('NCAAMB', 'Tennessee State Tigers'): 7,
    ('NCAAMB', 'Colgate Raiders'): 7,
    ('NCAAMB', 'Tennessee Tech Golden Eagles'): 7,
    ('NCAAMB', 'Lamar Cardinals'): 7,
    ('NCAAMB', 'New Orleans Privateers'): 7,
    ('NCAAMB', 'UT Rio Grande Valley Vaqueros'): 7,
    ('NCAAMB', 'Coastal Carolina Chanticleers'): 7,
    ('NCAAMB', 'Georgia State Panthers'): 7,
    ('NCAAMB', 'Louisiana Ragin\' Cajuns'): 7,
    ('NCAAMB', 'UT Arlington Mavericks'): 7,
    ('NCAAMB', 'UMBC Retrievers'): 6,
    ('NCAAMB', 'Rice Owls'): 6,
    ('NCAAMB', 'Lipscomb Bisons'): 6,
    ('NCAAMB', 'Presbyterian Blue Hose'): 6,
    ('NCAAMB', 'UNC Asheville Bulldogs'): 6,
    ('NCAAMB', 'Cal State Northridge Matadors'): 6,
    ('NCAAMB', 'Long Beach State Beach'): 6,
    ('NCAAMB', 'UC Riverside Highlanders'): 6,
    ('NCAAMB', 'Elon Phoenix'): 6,
    ('NCAAMB', 'Monmouth Hawks'): 6,
    ('NCAAMB', 'Delaware Blue Hens'): 6,
    ('NCAAMB', 'Missouri State Bears'): 6,
    ('NCAAMB', 'Detroit Mercy Titans'): 6,
    ('NCAAMB', 'Milwaukee Panthers'): 6,
    ('NCAAMB', 'Northern Illinois Huskies'): 6,
    ('NCAAMB', 'Youngstown State Penguins'): 6,
    ('NCAAMB', 'Iona Gaels'): 6,
    ('NCAAMB', 'Southern Illinois Salukis'): 6,
    ('NCAAMB', 'SIU Edwardsville Cougars'): 6,
    ('NCAAMB', 'Lehigh Mountain Hawks'): 6,
    ('NCAAMB', 'Mercer Bears'): 6,
    ('NCAAMB', 'Southeastern Louisiana Lions'): 6,
    ('NCAAMB', 'Oral Roberts Golden Eagles'): 6,
    ('NCAAMB', 'South Dakota State Jackrabbits'): 6,
    ('NCAAMB', 'Old Dominion Monarchs'): 6,
    ('NCAAMB', 'South Alabama Jaguars'): 6,
    ('NCAAMB', 'Eastern Kentucky Colonels'): 6,
    ('NCAAMB', 'Denver Pioneers'): 6,
    ('NCAAMB', 'Albany Great Danes'): 5,
    ('NCAAMB', 'Florida Gulf Coast Eagles'): 5,
    ('NCAAMB', 'Stetson Hatters'): 5,
    ('NCAAMB', 'Radford Highlanders'): 5,
    ('NCAAMB', 'Northeastern Huskies'): 5,
    ('NCAAMB', 'Cleveland State Vikings'): 5,
    ('NCAAMB', 'IU Indy Jaguars'): 5,
    ('NCAAMB', 'Purdue Fort Wayne Mastodons'): 5,
    ('NCAAMB', 'Siena Saints'): 5,
    ('NCAAMB', 'Ball State Cardinals'): 5,
    ('NCAAMB', 'Evansville Purple Aces'): 5,
    ('NCAAMB', 'Air Force Falcons'): 5,
    ('NCAAMB', 'LIU Sharks'): 5,
    ('NCAAMB', 'Lindenwood Lions'): 5,
    ('NCAAMB', 'Chattanooga Mocs'): 5,
    ('NCAAMB', 'Samford Bulldogs'): 5,
    ('NCAAMB', 'Wofford Terriers'): 5,
    ('NCAAMB', 'Alabama State Hornets'): 5,
    ('NCAAMB', 'Florida A&M Rattlers'): 5,
    ('NCAAMB', 'Jackson State Tigers'): 5,
    ('NCAAMB', 'Omaha Mavericks'): 5,
    ('NCAAMB', 'South Dakota Coyotes'): 5,
    ('NCAAMB', 'Appalachian State Mountaineers'): 5,
    ('NCAAMB', 'Marshall Thundering Herd'): 5,
    ('NCAAMB', 'Louisiana Tech Bulldogs'): 5,
    ('NCAAMB', 'Little Rock Trojans'): 5,
    ('NCAAMB', 'UMass Lowell River Hawks'): 4,
    ('NCAAMB', 'New Hampshire Wildcats'): 4,
    ('NCAAMB', 'NJIT Highlanders'): 4,
    ('NCAAMB', 'Bellarmine Knights'): 4,
    ('NCAAMB', 'Idaho State Bengals'): 4,
    ('NCAAMB', 'Northern Arizona Lumberjacks'): 4,
    ('NCAAMB', 'Southern Utah Thunderbirds'): 4,
    ('NCAAMB', 'Weber State Wildcats'): 4,
    ('NCAAMB', 'Charleston Southern Buccaneers'): 4,
    ('NCAAMB', 'Cal State Bakersfield Roadrunners'): 4,
    ('NCAAMB', 'Drexel Dragons'): 4,
    ('NCAAMB', 'NC A&T Aggies'): 4,
    ('NCAAMB', 'Dartmouth Big Green'): 4,
    ('NCAAMB', 'Mount St. Mary\'s Mountaineers'): 4,
    ('NCAAMB', 'Niagara Purple Eagles'): 4,
    ('NCAAMB', 'Sacred Heart Pioneers'): 4,
    ('NCAAMB', 'Mercyhurst Lakers'): 4,
    ('NCAAMB', 'Morehead State Eagles'): 4,
    ('NCAAMB', 'Southern Indiana Screaming Eagles'): 4,
    ('NCAAMB', 'UT Martin Skyhawks'): 4,
    ('NCAAMB', 'Boston University Terriers'): 4,
    ('NCAAMB', 'Navy Midshipmen'): 4,
    ('NCAAMB', 'UNC Greensboro Spartans'): 4,
    ('NCAAMB', 'East Texas A&M Lions'): 4,
    ('NCAAMB', 'Houston Christian Huskies'): 4,
    ('NCAAMB', 'Nicholls State Colonels'): 4,
    ('NCAAMB', 'Northwestern State Demons'): 4,
    ('NCAAMB', 'Alabama A&M Bulldogs'): 4,
    ('NCAAMB', 'Prairie View A&M Panthers'): 4,
    ('NCAAMB', 'North Dakota Fighting Hawks'): 4,
    ('NCAAMB', 'Abilene Christian Wildcats'): 4,
    ('NCAAMB', 'North Alabama Lions'): 4,
    ('NCAAMB', 'West Georgia Wolves'): 4,
    ('NCAAMB', 'Binghamton Bearcats'): 3,
    ('NCAAMB', 'Bryant Bulldogs'): 3,
    ('NCAAMB', 'Maine Black Bears'): 3,
    ('NCAAMB', 'North Florida Ospreys'): 3,
    ('NCAAMB', 'Utah Tech Trailblazers'): 3,
    ('NCAAMB', 'USC Upstate Spartans'): 3,
    ('NCAAMB', 'Canisius Golden Griffins'): 3,
    ('NCAAMB', 'Manhattan Jaspers'): 3,
    ('NCAAMB', 'Delaware State Hornets'): 3,
    ('NCAAMB', 'Norfolk State Spartans'): 3,
    ('NCAAMB', 'Central Connecticut Blue Devils'): 3,
    ('NCAAMB', 'Chicago State Cougars'): 3,
    ('NCAAMB', 'Fairleigh Dickinson Knights'): 3,
    ('NCAAMB', 'Le Moyne Dolphins'): 3,
    ('NCAAMB', 'Stonehill Skyhawks'): 3,
    ('NCAAMB', 'Wagner Seahawks'): 3,
    ('NCAAMB', 'Eastern Illinois Panthers'): 3,
    ('NCAAMB', 'Western Illinois Leathernecks'): 3,
    ('NCAAMB', 'Bucknell Bison'): 3,
    ('NCAAMB', 'Holy Cross Crusaders'): 3,
    ('NCAAMB', 'Lafayette Leopards'): 3,
    ('NCAAMB', 'Loyola Maryland Greyhounds'): 3,
    ('NCAAMB', 'Ole Miss Rebels'): 3,
    ('NCAAMB', 'The Citadel Bulldogs'): 3,
    ('NCAAMB', 'VMI Keydets'): 3,
    ('NCAAMB', 'Incarnate Word Cardinals'): 3,
    ('NCAAMB', 'Southern Jaguars'): 3,
    ('NCAAMB', 'Texas Southern Tigers'): 3,
    ('NCAAMB', 'Kansas City Roos'): 3,
    ('NCAAMB', 'Georgia Southern Eagles'): 3,
    ('NCAAMB', 'Louisiana-Monroe Warhawks'): 3,
    ('NCAAMB', 'Gardner-Webb Runnin\' Bulldogs'): 2,
    ('NCAAMB', 'Rider Broncs'): 2,
    ('NCAAMB', 'Coppin State Eagles'): 2,
    ('NCAAMB', 'Morgan State Bears'): 2,
    ('NCAAMB', 'North Carolina Central Eagles'): 2,
    ('NCAAMB', 'South Carolina State Bulldogs'): 2,
    ('NCAAMB', 'New Haven Chargers'): 2,
    ('NCAAMB', 'Army Black Knights'): 2,
    ('NCAAMB', 'Alcorn State Braves'): 2,
    ('NCAAMB', 'Arkansas-Pine Bluff Golden Lions'): 2,
    ('NCAAMB', 'Grambling State Tigers'): 2,
    ('NCAAMB', 'West Florida Argonauts'): 1,
    ('NCAAMB', 'Maryland Eastern Shore Hawks'): 1,
    ('NCAAMB', 'Mississippi Valley State Delta Devils'): 1,
    # --- NCAAWB ---
    ('NCAAWB', 'UCLA Bruins'): 32,
    ('NCAAWB', 'UConn Huskies'): 31,
    ('NCAAWB', 'South Carolina Gamecocks'): 31,
    ('NCAAWB', 'LSU Tigers'): 30,
    ('NCAAWB', 'Texas Longhorns'): 30,
    ('NCAAWB', 'Duke Blue Devils'): 28,
    ('NCAAWB', 'Michigan Wolverines'): 28,
    ('NCAAWB', 'TCU Horned Frogs'): 27,
    ('NCAAWB', 'Oklahoma Sooners'): 27,
    ('NCAAWB', 'Vanderbilt Commodores'): 27,
    ('NCAAWB', 'Louisville Cardinals'): 26,
    ('NCAAWB', 'North Carolina Tar Heels'): 26,
    ('NCAAWB', 'Notre Dame Fighting Irish'): 26,
    ('NCAAWB', 'Iowa Hawkeyes'): 26,
    ('NCAAWB', 'West Virginia Mountaineers'): 26,
    ('NCAAWB', 'Kentucky Wildcats'): 26,
    ('NCAAWB', 'Maryland Terrapins'): 25,
    ('NCAAWB', 'Michigan State Spartans'): 25,
    ('NCAAWB', 'Minnesota Golden Gophers'): 25,
    ('NCAAWB', 'Ohio State Buckeyes'): 25,
    ('NCAAWB', 'Mississippi State Bulldogs'): 25,
    ('NCAAWB', 'Virginia Cavaliers'): 24,
    ('NCAAWB', 'Washington Huskies'): 24,
    ('NCAAWB', 'Columbia Lions'): 24,
    ('NCAAWB', 'Alabama Crimson Tide'): 24,
    ('NCAAWB', 'NC State Wolfpack'): 23,
    ('NCAAWB', 'Virginia Tech Hokies'): 23,
    ('NCAAWB', 'Villanova Wildcats'): 23,
    ('NCAAWB', 'Illinois Fighting Illini'): 23,
    ('NCAAWB', 'Nebraska Cornhuskers'): 23,
    ('NCAAWB', 'Oregon Ducks'): 23,
    ('NCAAWB', 'USC Trojans'): 22,
    ('NCAAWB', 'Houston Cougars'): 22,
    ('NCAAWB', 'Fairfield Stags'): 22,
    ('NCAAWB', 'Gonzaga Bulldogs'): 22,
    ('NCAAWB', 'Miami (FL) Hurricanes'): 21,
    ('NCAAWB', 'St. John\'s Red Storm'): 21,
    ('NCAAWB', 'Kansas Jayhawks'): 21,
    ('NCAAWB', 'Texas Tech Red Raiders'): 21,
    ('NCAAWB', 'Ohio Bobcats'): 21,
    ('NCAAWB', 'Marquette Golden Eagles'): 20,
    ('NCAAWB', 'Indiana Hoosiers'): 20,
    ('NCAAWB', 'Purdue Boilermakers'): 20,
    ('NCAAWB', 'Iowa State Cyclones'): 20,
    ('NCAAWB', 'Arkansas Razorbacks'): 20,
    ('NCAAWB', 'Clemson Tigers'): 19,
    ('NCAAWB', 'Creighton Bluejays'): 19,
    ('NCAAWB', 'BYU Cougars'): 19,
    ('NCAAWB', 'Auburn Tigers'): 19,
    ('NCAAWB', 'SMU Mustangs'): 18,
    ('NCAAWB', 'Wisconsin Badgers'): 18,
    ('NCAAWB', 'Baylor Bears'): 18,
    ('NCAAWB', 'Cincinnati Bearcats'): 18,
    ('NCAAWB', 'UCF Knights'): 18,
    ('NCAAWB', 'Texas A&M Aggies'): 18,
    ('NCAAWB', 'Syracuse Orange'): 17,
    ('NCAAWB', 'VCU Rams'): 17,
    ('NCAAWB', 'Providence Friars'): 17,
    ('NCAAWB', 'Xavier Musketeers'): 17,
    ('NCAAWB', 'Oklahoma State Cowboys'): 17,
    ('NCAAWB', 'Grand Canyon Antelopes'): 17,
    ('NCAAWB', 'San Diego State Aztecs'): 17,
    ('NCAAWB', 'Wichita State Shockers'): 16,
    ('NCAAWB', 'Saint Louis Billikens'): 16,
    ('NCAAWB', 'DePaul Blue Demons'): 16,
    ('NCAAWB', 'High Point Panthers'): 16,
    ('NCAAWB', 'Arizona State Sun Devils'): 16,
    ('NCAAWB', 'Utah State Aggies'): 16,
    ('NCAAWB', 'Saint Mary\'s Gaels'): 16,
    ('NCAAWB', 'Tulsa Golden Hurricane'): 15,
    ('NCAAWB', 'Florida State Seminoles'): 15,
    ('NCAAWB', 'Pittsburgh Panthers'): 15,
    ('NCAAWB', 'Dayton Flyers'): 15,
    ('NCAAWB', 'Seton Hall Pirates'): 15,
    ('NCAAWB', 'Northwestern Wildcats'): 15,
    ('NCAAWB', 'Rutgers Scarlet Knights'): 15,
    ('NCAAWB', 'California Golden Bears'): 14,
    ('NCAAWB', 'George Washington Revolutionaries'): 14,
    ('NCAAWB', 'Georgetown Hoyas'): 14,
    ('NCAAWB', 'Kansas State Wildcats'): 14,
    ('NCAAWB', 'Iona Gaels'): 14,
    ('NCAAWB', 'Buffalo Bulls'): 14,
    ('NCAAWB', 'Nevada Wolf Pack'): 14,
    ('NCAAWB', 'Boise State Broncos'): 14,
    ('NCAAWB', 'Colorado State Rams'): 14,
    ('NCAAWB', 'McNeese State Cowboys'): 14,
    ('NCAAWB', 'Charlotte 49ers'): 13,
    ('NCAAWB', 'South Florida Bulls'): 13,
    ('NCAAWB', 'Stanford Cardinal'): 13,
    ('NCAAWB', 'Wake Forest Demon Deacons'): 13,
    ('NCAAWB', 'George Mason Patriots'): 13,
    ('NCAAWB', 'Butler Bulldogs'): 13,
    ('NCAAWB', 'UC Santa Barbara Gauchos'): 13,
    ('NCAAWB', 'Miami (OH) RedHawks'): 13,
    ('NCAAWB', 'UIC Flames'): 13,
    ('NCAAWB', 'UNLV Rebels'): 13,
    ('NCAAWB', 'Oregon State Beavers'): 13,
    ('NCAAWB', 'Santa Clara Broncos'): 13,
    ('NCAAWB', 'Memphis Tigers'): 12,
    ('NCAAWB', 'North Texas Mean Green'): 12,
    ('NCAAWB', 'UAB Blazers'): 12,
    ('NCAAWB', 'Boston College Eagles'): 12,
    ('NCAAWB', 'Georgia Tech Yellow Jackets'): 12,
    ('NCAAWB', 'Davidson Wildcats'): 12,
    ('NCAAWB', 'Richmond Spiders'): 12,
    ('NCAAWB', 'Penn State Nittany Lions'): 12,
    ('NCAAWB', 'UNC Wilmington Seahawks'): 12,
    ('NCAAWB', 'Western Kentucky Hilltoppers'): 12,
    ('NCAAWB', 'Penn Quakers'): 12,
    ('NCAAWB', 'Akron Zips'): 12,
    ('NCAAWB', 'Belmont Bruins'): 12,
    ('NCAAWB', 'Illinois State Redbirds'): 12,
    ('NCAAWB', 'Murray State Racers'): 12,
    ('NCAAWB', 'Georgia Bulldogs'): 12,
    ('NCAAWB', 'Florida Atlantic Owls'): 11,
    ('NCAAWB', 'Fordham Rams'): 11,
    ('NCAAWB', 'Saint Joseph\'s Hawks'): 11,
    ('NCAAWB', 'St. Bonaventure Bonnies'): 11,
    ('NCAAWB', 'UC Irvine Anteaters'): 11,
    ('NCAAWB', 'UC San Diego Tritons'): 11,
    ('NCAAWB', 'Utah Valley Wolverines'): 11,
    ('NCAAWB', 'Kennesaw State Owls'): 11,
    ('NCAAWB', 'Harvard Crimson'): 11,
    ('NCAAWB', 'Toledo Rockets'): 11,
    ('NCAAWB', 'Northern Iowa Panthers'): 11,
    ('NCAAWB', 'Hawaii Rainbow Warriors'): 11,
    ('NCAAWB', 'Wyoming Cowboys'): 11,
    ('NCAAWB', 'Fresno State Bulldogs'): 11,
    ('NCAAWB', 'Texas State Bobcats'): 11,
    ('NCAAWB', 'Florida Gators'): 11,
    ('NCAAWB', 'Stephen F. Austin Lumberjacks'): 11,
    ('NCAAWB', 'Loyola Marymount Lions'): 11,
    ('NCAAWB', 'Pacific Tigers'): 11,
    ('NCAAWB', 'San Diego Toreros'): 11,
    ('NCAAWB', 'Temple Owls'): 10,
    ('NCAAWB', 'Duquesne Dukes'): 10,
    ('NCAAWB', 'La Salle Explorers'): 10,
    ('NCAAWB', 'Loyola Chicago Ramblers'): 10,
    ('NCAAWB', 'Rhode Island Rams'): 10,
    ('NCAAWB', 'Sacramento State Hornets'): 10,
    ('NCAAWB', 'Liberty Flames'): 10,
    ('NCAAWB', 'Middle Tennessee Blue Raiders'): 10,
    ('NCAAWB', 'New Mexico State Aggies'): 10,
    ('NCAAWB', 'Robert Morris Colonials'): 10,
    ('NCAAWB', 'Wright State Raiders'): 10,
    ('NCAAWB', 'Princeton Tigers'): 10,
    ('NCAAWB', 'Kent State Golden Flashes'): 10,
    ('NCAAWB', 'Drake Bulldogs'): 10,
    ('NCAAWB', 'Valparaiso Beacons'): 10,
    ('NCAAWB', 'UC Davis Aggies'): 10,
    ('NCAAWB', 'New Mexico Lobos'): 10,
    ('NCAAWB', 'UTEP Miners'): 10,
    ('NCAAWB', 'Tennessee Volunteers'): 10,
    ('NCAAWB', 'North Dakota State Bison'): 10,
    ('NCAAWB', 'St. Thomas Tommies'): 10,
    ('NCAAWB', 'James Madison Dukes'): 10,
    ('NCAAWB', 'Tarleton State Texans'): 10,
    ('NCAAWB', 'Pepperdine Waves'): 10,
    ('NCAAWB', 'Seattle Redhawks'): 10,
    ('NCAAWB', 'Tulane Green Wave'): 9,
    ('NCAAWB', 'Montana State Bobcats'): 9,
    ('NCAAWB', 'California Baptist Lancers'): 9,
    ('NCAAWB', 'Campbell Fighting Camels'): 9,
    ('NCAAWB', 'Hofstra Pride'): 9,
    ('NCAAWB', 'Towson Tigers'): 9,
    ('NCAAWB', 'Sam Houston Bearkats'): 9,
    ('NCAAWB', 'Green Bay Phoenix'): 9,
    ('NCAAWB', 'Merrimack Warriors'): 9,
    ('NCAAWB', 'Bowling Green Falcons'): 9,
    ('NCAAWB', 'Eastern Michigan Eagles'): 9,
    ('NCAAWB', 'Western Michigan Broncos'): 9,
    ('NCAAWB', 'San Jose State Spartans'): 9,
    ('NCAAWB', 'Washington State Cougars'): 9,
    ('NCAAWB', 'East Tennessee State Buccaneers'): 9,
    ('NCAAWB', 'Furman Paladins'): 9,
    ('NCAAWB', 'Western Carolina Catamounts'): 9,
    ('NCAAWB', 'Texas A&M-Corpus Christi Islanders'): 9,
    ('NCAAWB', 'Troy Trojans'): 9,
    ('NCAAWB', 'Austin Peay Governors'): 9,
    ('NCAAWB', 'Central Arkansas Bears'): 9,
    ('NCAAWB', 'San Francisco Dons'): 9,
    ('NCAAWB', 'Vermont Catamounts'): 8,
    ('NCAAWB', 'East Carolina Pirates'): 8,
    ('NCAAWB', 'UTSA Roadrunners'): 8,
    ('NCAAWB', 'Queens Royals'): 8,
    ('NCAAWB', 'Eastern Washington Eagles'): 8,
    ('NCAAWB', 'Idaho Vandals'): 8,
    ('NCAAWB', 'Montana Grizzlies'): 8,
    ('NCAAWB', 'Hampton Pirates'): 8,
    ('NCAAWB', 'William & Mary Tribe'): 8,
    ('NCAAWB', 'FIU Panthers'): 8,
    ('NCAAWB', 'Yale Bulldogs'): 8,
    ('NCAAWB', 'Marist Red Foxes'): 8,
    ('NCAAWB', 'Central Michigan Chippewas'): 8,
    ('NCAAWB', 'Bradley Braves'): 8,
    ('NCAAWB', 'Southeast Missouri State Redhawks'): 8,
    ('NCAAWB', 'American Eagles'): 8,
    ('NCAAWB', 'Lamar Cardinals'): 8,
    ('NCAAWB', 'UT Rio Grande Valley Vaqueros'): 8,
    ('NCAAWB', 'Bethune-Cookman Wildcats'): 8,
    ('NCAAWB', 'Arkansas State Red Wolves'): 8,
    ('NCAAWB', 'Southern Miss Golden Eagles'): 8,
    ('NCAAWB', 'Jacksonville Dolphins'): 7,
    ('NCAAWB', 'Northern Colorado Bears'): 7,
    ('NCAAWB', 'Portland State Vikings'): 7,
    ('NCAAWB', 'Longwood Lancers'): 7,
    ('NCAAWB', 'Winthrop Eagles'): 7,
    ('NCAAWB', 'Colorado Buffaloes'): 7,
    ('NCAAWB', 'Cal Poly Mustangs'): 7,
    ('NCAAWB', 'Stony Brook Seawolves'): 7,
    ('NCAAWB', 'Jacksonville State Gamecocks'): 7,
    ('NCAAWB', 'Northern Kentucky Norse'): 7,
    ('NCAAWB', 'Oakland Golden Grizzlies'): 7,
    ('NCAAWB', 'Brown Bears'): 7,
    ('NCAAWB', 'Cornell Big Red'): 7,
    ('NCAAWB', 'Howard Bison'): 7,
    ('NCAAWB', 'Indiana State Sycamores'): 7,
    ('NCAAWB', 'Tennessee State Tigers'): 7,
    ('NCAAWB', 'Colgate Raiders'): 7,
    ('NCAAWB', 'Tennessee Tech Golden Eagles'): 7,
    ('NCAAWB', 'New Orleans Privateers'): 7,
    ('NCAAWB', 'Coastal Carolina Chanticleers'): 7,
    ('NCAAWB', 'Georgia State Panthers'): 7,
    ('NCAAWB', 'Louisiana Ragin\' Cajuns'): 7,
    ('NCAAWB', 'UT Arlington Mavericks'): 7,
    ('NCAAWB', 'Portland Pilots'): 7,
    ('NCAAWB', 'Rice Owls'): 6,
    ('NCAAWB', 'Presbyterian Blue Hose'): 6,
    ('NCAAWB', 'Cal State Fullerton Titans'): 6,
    ('NCAAWB', 'Cal State Northridge Matadors'): 6,
    ('NCAAWB', 'Long Beach State Beach'): 6,
    ('NCAAWB', 'Elon Phoenix'): 6,
    ('NCAAWB', 'Monmouth Hawks'): 6,
    ('NCAAWB', 'Delaware Blue Hens'): 6,
    ('NCAAWB', 'Detroit Mercy Titans'): 6,
    ('NCAAWB', 'Milwaukee Panthers'): 6,
    ('NCAAWB', 'Northern Illinois Huskies'): 6,
    ('NCAAWB', 'Quinnipiac Bobcats'): 6,
    ('NCAAWB', 'Southern Illinois Salukis'): 6,
    ('NCAAWB', 'SIU Edwardsville Cougars'): 6,
    ('NCAAWB', 'Lehigh Mountain Hawks'): 6,
    ('NCAAWB', 'Mercer Bears'): 6,
    ('NCAAWB', 'Southeastern Louisiana Lions'): 6,
    ('NCAAWB', 'Oral Roberts Golden Eagles'): 6,
    ('NCAAWB', 'South Dakota State Jackrabbits'): 6,
    ('NCAAWB', 'Old Dominion Monarchs'): 6,
    ('NCAAWB', 'South Alabama Jaguars'): 6,
    ('NCAAWB', 'Eastern Kentucky Colonels'): 6,
    ('NCAAWB', 'Denver Pioneers'): 6,
    ('NCAAWB', 'UMBC Retrievers'): 5,
    ('NCAAWB', 'Florida Gulf Coast Eagles'): 5,
    ('NCAAWB', 'Lipscomb Bisons'): 5,
    ('NCAAWB', 'Stetson Hatters'): 5,
    ('NCAAWB', 'Radford Highlanders'): 5,
    ('NCAAWB', 'UNC Asheville Bulldogs'): 5,
    ('NCAAWB', 'UC Riverside Highlanders'): 5,
    ('NCAAWB', 'Northeastern Huskies'): 5,
    ('NCAAWB', 'Missouri State Bears'): 5,
    ('NCAAWB', 'Cleveland State Vikings'): 5,
    ('NCAAWB', 'IU Indy Jaguars'): 5,
    ('NCAAWB', 'Purdue Fort Wayne Mastodons'): 5,
    ('NCAAWB', 'Youngstown State Penguins'): 5,
    ('NCAAWB', 'Siena Saints'): 5,
    ('NCAAWB', 'Ball State Cardinals'): 5,
    ('NCAAWB', 'Evansville Purple Aces'): 5,
    ('NCAAWB', 'Air Force Falcons'): 5,
    ('NCAAWB', 'LIU Sharks'): 5,
    ('NCAAWB', 'Missouri Tigers'): 5,
    ('NCAAWB', 'Chattanooga Mocs'): 5,
    ('NCAAWB', 'Samford Bulldogs'): 5,
    ('NCAAWB', 'Wofford Terriers'): 5,
    ('NCAAWB', 'Alabama State Hornets'): 5,
    ('NCAAWB', 'Appalachian State Mountaineers'): 5,
    ('NCAAWB', 'Louisiana Tech Bulldogs'): 5,
    ('NCAAWB', 'Little Rock Trojans'): 5,
    ('NCAAWB', 'Albany Great Danes'): 4,
    ('NCAAWB', 'New Hampshire Wildcats'): 4,
    ('NCAAWB', 'Bellarmine Knights'): 4,
    ('NCAAWB', 'Southern Utah Thunderbirds'): 4,
    ('NCAAWB', 'Weber State Wildcats'): 4,
    ('NCAAWB', 'Utah Utes'): 4,
    ('NCAAWB', 'Drexel Dragons'): 4,
    ('NCAAWB', 'NC A&T Aggies'): 4,
    ('NCAAWB', 'Mount St. Mary\'s Mountaineers'): 4,
    ('NCAAWB', 'Sacred Heart Pioneers'): 4,
    ('NCAAWB', 'Lindenwood Lions'): 4,
    ('NCAAWB', 'Southern Indiana Screaming Eagles'): 4,
    ('NCAAWB', 'Boston University Terriers'): 4,
    ('NCAAWB', 'UNC Greensboro Spartans'): 4,
    ('NCAAWB', 'Houston Christian Huskies'): 4,
    ('NCAAWB', 'Nicholls State Colonels'): 4,
    ('NCAAWB', 'Northwestern State Demons'): 4,
    ('NCAAWB', 'Florida A&M Rattlers'): 4,
    ('NCAAWB', 'Jackson State Tigers'): 4,
    ('NCAAWB', 'Prairie View A&M Panthers'): 4,
    ('NCAAWB', 'Southern Jaguars'): 4,
    ('NCAAWB', 'Omaha Mavericks'): 4,
    ('NCAAWB', 'South Dakota Coyotes'): 4,
    ('NCAAWB', 'Marshall Thundering Herd'): 4,
    ('NCAAWB', 'North Alabama Lions'): 4,
    ('NCAAWB', 'West Georgia Wolves'): 4,
    ('NCAAWB', 'Bryant Bulldogs'): 3,
    ('NCAAWB', 'Maine Black Bears'): 3,
    ('NCAAWB', 'UMass Lowell River Hawks'): 3,
    ('NCAAWB', 'NJIT Highlanders'): 3,
    ('NCAAWB', 'North Florida Ospreys'): 3,
    ('NCAAWB', 'Idaho State Bengals'): 3,
    ('NCAAWB', 'Northern Arizona Lumberjacks'): 3,
    ('NCAAWB', 'Charleston Southern Buccaneers'): 3,
    ('NCAAWB', 'USC Upstate Spartans'): 3,
    ('NCAAWB', 'Arizona Wildcats'): 3,
    ('NCAAWB', 'Cal State Bakersfield Roadrunners'): 3,
    ('NCAAWB', 'Charleston Cougars'): 3,
    ('NCAAWB', 'Dartmouth Big Green'): 3,
    ('NCAAWB', 'Canisius Golden Griffins'): 3,
    ('NCAAWB', 'Manhattan Jaspers'): 3,
    ('NCAAWB', 'Niagara Purple Eagles'): 3,
    ('NCAAWB', 'UMass Minutemen'): 3,
    ('NCAAWB', 'Le Moyne Dolphins'): 3,
    ('NCAAWB', 'Mercyhurst Lakers'): 3,
    ('NCAAWB', 'Morehead State Eagles'): 3,
    ('NCAAWB', 'UT Martin Skyhawks'): 3,
    ('NCAAWB', 'Navy Midshipmen'): 3,
    ('NCAAWB', 'East Texas A&M Lions'): 3,
    ('NCAAWB', 'Alabama A&M Bulldogs'): 3,
    ('NCAAWB', 'North Dakota Fighting Hawks'): 3,
    ('NCAAWB', 'Louisiana-Monroe Warhawks'): 3,
    ('NCAAWB', 'Abilene Christian Wildcats'): 3,
    ('NCAAWB', 'Binghamton Bearcats'): 2,
    ('NCAAWB', 'Utah Tech Trailblazers'): 2,
    ('NCAAWB', 'Gardner-Webb Runnin\' Bulldogs'): 2,
    ('NCAAWB', 'Delaware State Hornets'): 2,
    ('NCAAWB', 'Norfolk State Spartans'): 2,
    ('NCAAWB', 'Central Connecticut Blue Devils'): 2,
    ('NCAAWB', 'Chicago State Cougars'): 2,
    ('NCAAWB', 'Fairleigh Dickinson Knights'): 2,
    ('NCAAWB', 'New Haven Chargers'): 2,
    ('NCAAWB', 'Stonehill Skyhawks'): 2,
    ('NCAAWB', 'Wagner Seahawks'): 2,
    ('NCAAWB', 'Eastern Illinois Panthers'): 2,
    ('NCAAWB', 'Western Illinois Leathernecks'): 2,
    ('NCAAWB', 'Bucknell Bison'): 2,
    ('NCAAWB', 'Holy Cross Crusaders'): 2,
    ('NCAAWB', 'Lafayette Leopards'): 2,
    ('NCAAWB', 'Loyola Maryland Greyhounds'): 2,
    ('NCAAWB', 'Incarnate Word Cardinals'): 2,
    ('NCAAWB', 'Texas Southern Tigers'): 2,
    ('NCAAWB', 'Kansas City Roos'): 2,
    ('NCAAWB', 'Georgia Southern Eagles'): 2,
    ('NCAAWB', 'West Florida Argonauts'): 1,
    ('NCAAWB', 'Rider Broncs'): 1,
    ('NCAAWB', 'Coppin State Eagles'): 1,
    ('NCAAWB', 'Maryland Eastern Shore Hawks'): 1,
    ('NCAAWB', 'Morgan State Bears'): 1,
    ('NCAAWB', 'North Carolina Central Eagles'): 1,
    ('NCAAWB', 'South Carolina State Bulldogs'): 1,
    ('NCAAWB', 'Army Black Knights'): 1,
    ('NCAAWB', 'Ole Miss Rebels'): 1,
    ('NCAAWB', 'Alcorn State Braves'): 1,
    ('NCAAWB', 'Arkansas-Pine Bluff Golden Lions'): 1,
    ('NCAAWB', 'Grambling State Tigers'): 1,
    ('NCAAWB', 'Mississippi Valley State Delta Devils'): 1,
    # --- ATP ---
    ('ATP', 'United States'): 79,
    ('ATP', 'Italy'): 75,
    ('ATP', 'France'): 56,
    ('ATP', 'Spain'): 54,
    ('ATP', 'Argentina'): 38,
    ('ATP', 'Germany'): 29,
    ('ATP', 'Great Britain'): 28,
    ('ATP', 'Australia'): 27,
    ('ATP', 'Russia'): 23,
    ('ATP', 'Czech Republic'): 22,
    ('ATP', 'Canada'): 20,
    ('ATP', 'Serbia'): 19,
    ('ATP', 'Belgium'): 17,
    ('ATP', 'Brazil'): 11,
    ('ATP', 'Kazakhstan'): 10,
    ('ATP', 'Netherlands'): 10,
    ('ATP', 'Japan'): 10,
    ('ATP', 'Croatia'): 9,
    ('ATP', 'Switzerland'): 9,
    ('ATP', 'Portugal'): 8,
    ('ATP', 'Chile'): 8,
    ('ATP', 'China'): 8,
    ('ATP', 'Austria'): 8,
    ('ATP', 'Hungary'): 7,
    ('ATP', 'Norway'): 7,
    ('ATP', 'Poland'): 6,
    ('ATP', 'Peru'): 6,
    ('ATP', 'Monaco'): 6,
    ('ATP', 'Denmark'): 5,
    ('ATP', 'Greece'): 5,
    ('ATP', 'Bolivia'): 4,
    ('ATP', 'Hong Kong'): 3,
    ('ATP', 'Bosnia and Herzegovina'): 3,
    ('ATP', 'Paraguay'): 3,
    ('ATP', 'Lithuania'): 3,
    ('ATP', 'Slovakia'): 3,
    ('ATP', 'Colombia'): 3,
    ('ATP', 'South Africa'): 3,
    ('ATP', 'Chinese Taipei'): 3,
    ('ATP', 'Ecuador'): 3,
    ('ATP', 'Estonia'): 3,
    ('ATP', 'Georgia'): 2,
    ('ATP', 'Bulgaria'): 2,
    ('ATP', 'Luxembourg'): 2,
    ('ATP', 'Finland'): 2,
    ('ATP', 'Ukraine'): 2,
    ('ATP', 'Tunisia'): 2,
    ('ATP', 'Mexico'): 2,
    ('ATP', 'Uruguay'): 2,
    ('ATP', 'South Korea'): 2,
    ('ATP', 'Sweden'): 2,
    ('ATP', 'Dominican Republic'): 2,
    ('ATP', 'Moldova'): 1,
    ('ATP', 'Egypt'): 1,
    ('ATP', 'Algeria'): 1,
    ('ATP', 'Lebanon'): 1,
    ('ATP', 'Israel'): 1,
    ('ATP', 'Ivory Coast'): 1,
    ('ATP', 'Slovenia'): 1,
    ('ATP', 'Ireland'): 1,
    ('ATP', 'Venezuela'): 1,
    ('ATP', 'Indonesia'): 1,
    ('ATP', 'Pakistan'): 1,
    ('ATP', 'Morocco'): 1,
    ('ATP', 'New Zealand'): 1,
    ('ATP', 'Senegal'): 1,
    ('ATP', 'Iran'): 1,
    ('ATP', 'Uzbekistan'): 1,
    ('ATP', 'Cyprus'): 1,
    # --- WTA ---
    ('WTA', 'United States'): 70,
    ('WTA', 'Czech Republic'): 39,
    ('WTA', 'Russia'): 37,
    ('WTA', 'Belarus'): 23,
    ('WTA', 'Ukraine'): 22,
    ('WTA', 'Poland'): 18,
    ('WTA', 'Australia'): 16,
    ('WTA', 'Spain'): 16,
    ('WTA', 'China'): 15,
    ('WTA', 'Japan'): 15,
    ('WTA', 'Kazakhstan'): 15,
    ('WTA', 'France'): 14,
    ('WTA', 'Italy'): 14,
    ('WTA', 'Switzerland'): 13,
    ('WTA', 'Germany'): 11,
    ('WTA', 'Canada'): 11,
    ('WTA', 'Great Britain'): 10,
    ('WTA', 'Romania'): 9,
    ('WTA', 'Austria'): 8,
    ('WTA', 'Belgium'): 8,
    ('WTA', 'Croatia'): 6,
    ('WTA', 'Argentina'): 6,
    ('WTA', 'Uzbekistan'): 5,
    ('WTA', 'Hungary'): 5,
    ('WTA', 'Slovakia'): 5,
    ('WTA', 'Greece'): 5,
    ('WTA', 'Latvia'): 4,
    ('WTA', 'Colombia'): 4,
    ('WTA', 'Slovenia'): 4,
    ('WTA', 'Netherlands'): 4,
    ('WTA', 'Serbia'): 4,
    ('WTA', 'Philippines'): 4,
    ('WTA', 'Turkey'): 4,
    ('WTA', 'Thailand'): 3,
    ('WTA', 'Denmark'): 3,
    ('WTA', 'Indonesia'): 3,
    ('WTA', 'Egypt'): 3,
    ('WTA', 'Armenia'): 3,
    ('WTA', 'Andorra'): 2,
    ('WTA', 'Mexico'): 2,
    ('WTA', 'New Zealand'): 2,
    ('WTA', 'Kenya'): 1,
    ('WTA', 'Israel'): 1,
    ('WTA', 'Ecuador'): 1,
    ('WTA', 'Montenegro'): 1,
    ('WTA', 'Albania'): 1,
    ('WTA', 'Finland'): 1,
}


def calibrate(num_users: int) -> dict[tuple[str, str], int]:
    """Turns FALL_EV_RAW_SCORES into dollar defaults, per the module
    docstring: the worst team still needed to fill every user's roster in a
    league prices at $1, everything ranked above it scales the same factor
    (preserving relative spacing) rounded to whole dollars floored at $1,
    and everything ranked below that cutoff -- nobody's projected to need
    it at any price -- prices at $0."""
    num_users = max(num_users, 1)

    by_league: dict[str, list[tuple[str, int]]] = {}
    for (league, name), score in FALL_EV_RAW_SCORES.items():
        by_league.setdefault(league, []).append((name, score))

    result: dict[tuple[str, str], int] = {}
    for league, teams in by_league.items():
        # Stable sort: FALL_EV_RAW_SCORES already lists each league's teams
        # best-to-worst, so ties keep that original relative order.
        ranked = sorted(teams, key=lambda t: t[1], reverse=True)
        needed = ROSTER_LIMITS[league] * num_users
        cutoff_index = min(needed, len(ranked)) - 1
        anchor_score = ranked[cutoff_index][1]
        scale = 1.0 / anchor_score if anchor_score > 0 else 1.0

        for idx, (name, score) in enumerate(ranked):
            if idx < needed:
                result[(league, name)] = max(1, round(score * scale))
            else:
                result[(league, name)] = 0

    return result


def set_defaults() -> None:
    db = SessionLocal()
    try:
        num_users = db.query(User).count()
        calibrated = calibrate(num_users)

        updated = 0
        missing: list[str] = []
        for (league, name), value in calibrated.items():
            team = db.query(Team).filter(Team.league == league, Team.name == name).first()
            if team is None:
                missing.append(f"{league} {name}")
                continue
            team.default_value = value
            updated += 1
        db.commit()
        print(f"Calibrated against {num_users} users. Set default_value on {updated} teams.")
        if missing:
            print(f"Skipped {len(missing)} names not found in the Team table: {', '.join(missing)}")
    finally:
        db.close()


if __name__ == "__main__":
    set_defaults()
